all:
  lifetime: 300
  enabled: true
rss:
  lifetime: 3600
  enabled: true
preview:
  lifetime: 28800
  enabled: true
_widget:
  lifetime: 28800
  enabled: true
_duJour:
  lifetime: 86400
  enabled: true
_fiche:
  lifetime: 28800
  enabled: true
list:
  lifetime: 28800
  enabled: true
show:
  enabled: false
