default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     fr
    robots:       index, follow
    "twitter:card":   summary
    "twitter:site":   @RegardsCitoyens
    "twitter:title":  "NosDéputés.fr par Regards Citoyens"
    "twitter:description": "Observatoire citoyen de l'activité parlementaire à l'Assemblée nationale">
    "twitter:image": "http://www.regardscitoyens.org/wp-content/uploads/2009/10/logo_nosdeputes.png"
  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout
