---

- name: Variables crontab
  cron:
    env: yes
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    user: '{{ cpc_user }}'
  with_items:
    - name: PATH
      value: /usr/local/bin:/usr/bin:/bin
    - name: NDRUN
      value: sudo dc-{{ cpc_instance_name }} exec -T web

- name: Indexation solr
  cron:
    name: 'cpc_{{ cpc_instance_name }}_index_solr'
    minute: '*'
    job: '$NDRUN bash bin/indexSolr'
    state: present
    user: '{{ cpc_user }}'
  when: cpc_enable_cronjobs and cpc_solr

- name: Suppression indexation solr
  cron:
    name: 'cpc_{{ cpc_instance_name }}_index_solr'
    state: absent
    user: '{{ cpc_user }}'
  when: not (cpc_enable_cronjobs and cpc_solr)

- name: Envoi mails spoolés
  cron:
    name: 'cpc_{{ cpc_instance_name }}_spool_mail'
    minute: '*'
    job: '$NDRUN bash bin/sendSpoolMail'
    state: present
    user: '{{ cpc_user }}'
  when: cpc_enable_cronjobs and cpc_spool_mails

- name: Suppression envoi mails spoolés
  cron:
    name: 'cpc_{{ cpc_instance_name }}_spool_mail'
    state: absent
    user: '{{ cpc_user }}'
  when: not (cpc_enable_cronjobs and cpc_spool_mails)
